[package]
name = "orm_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.3"
chrono = "0.4.26"
diesel = { version = "2.1.0", features = ["postgres", "chrono", "numeric", "extras"] }
dotenv = "0.15.0"
